[workspace]
authors = ["Sabari Kumar <sabarinkumar@gmail.com>"]
channels = ["dglteam/label/th24_cu124", "conda-forge", "https://prefix.dev/conda-forge", ]
name = "confsweeper"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[system-requirements]
cuda = "12"

[dependencies]
python = ">=3.11, <3.13"
rdkit = "*"
pytorch-gpu = "==2.5.1"
torch-scatter = "==2.1.1"
pytorch_cluster = "==1.6.3"
dgl = {version = ">2.0.0", channel="dglteam/label/th24_cu124"}
jupyterlab = ">=4.5.1,<5"
openbabel = ">=3.1.1,<4"
click = ">=8.2.1,<9"
pytest = ">=8.4.2,<9"
pyyaml = ">=6.0.2,<7"
ipykernel = ">=7.1.0,<8"
nvmolkit = ">=0.3.0,<0.4"
crest = ">=3.0.2,<4"
numba = ">=0.63.1,<0.64"
spyrmsd = ">=0.9.0,<0.10"
cuequivariance-torch = ">=0.8.1,<0.9"
datamol = ">=0.12.5,<0.13"
ipywidgets = ">=8.1.8,<9"
nglview = ">=4.0,<5"
gudhi = ">=3.11.0,<4"

[pypi-dependencies]
confsweeper = {path = ".", editable = true}
numpy = "*"
pandas = ">=2.3.2, <3"
ase = ">=3.26.0, <4"
pre-commit = ">=4.3.0, <5"
isort = ">=6.0.1, <7"
black = ">=25.1.0, <26"
networkx = "*"
cclib = ">=1.8.1, <2"
mace-torch = ">=0.3.14, <0.4"

[activation.env]
CONDA_OVERRIDE_CUDA = "12.2"
